### ISSUE TITLE
GUI形式でMAP生成

### ISSUE THREAD

**Issue by batacosan** [hiro220/newGame#27]
■作業段階
1.グリッド表示
2.オブジェクト一覧の表示
3.オブジェクトの選択
4.グリッドクリックでオブジェクト表示
5.json形式でファイル保存
6.ファイルロードでMAP生成

**Comment by hiro220** [comment]
### jsonファイルの形式
- "object" : 各オブジェクトのリスト

#### 各オブジェクトの形式
- "name" : オブジェクト識別子
- "x" : x座標
- "y" : y座標
- "args" : その他引数をリストで
