### ISSUE TITLE
GUIマップ作成で配置されたエネミーに必須の引数が足らないので、エネミーを配置するとエラーが出る

### ISSUE THREAD

**Issue by hiro220** [hiro220/newGame#46]
### 状況
GUIマップ作成のため、いったん使いずらいplayer引数を指定なしにしたままにしている。
__init__以外で該当の変数をセットすることがないため現状エネミーを配置したマップは動作しない。

### 解決案
- GUIマップ作成側でどうにか引数に指定できるようにする
- playerをセットする関数を用意し、適切な場所でセットする
- エネミーグループのupdateの引数にして、マップ作成では関与しない

上二つは結局GUIマップ作成側でplayerを認識してセットする必要があるから実質同じ処理が必要。
比較的難しいと思う。
一番下の案が変更点が少なくて影響を及ぼしそうな場所も少ないから、採用したい案。

**Comment by milledrian** [comment]
修正済み
